n_epochs: 4096
seed: 4

data:
  batch_size: 32
  scale_method: per_element_force_rms_scale
  shift_method: per_element_regression_shift
  shift_options:
    energy_regularisation: 1.0
  valid_batch_size: 32
loss:
- name: energy
- name: forces
  weight: 4.0
metrics:
- name: energy
  reductions:
  - mae
- name: forces
  reductions:
  - mae
  - mse
model:
  b_init: normal
  calc_stress: true
  descriptor_dtype: fp32
  emb_init: uniform
  n_basis: 7
  n_radial: 5
  nn:
  - 512
  - 512
  r_max: 5.5
  r_min: 0.5
  readout_dtype: fp32
  scale_shift_dtype: fp32
  use_zbl: true
optimizer:
  emb_lr: 0.01
  nn_lr: 0.005
  opt_name: adam
  scale_lr: 0.001
  shift_lr: 0.05
  zbl_lr: 0.001